language: python

branches:
  only:
    - master

virtualenv:
  system_site_packages: true

python:
  - "2.7"

install:
  - pip install -r requirements.pip

before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - paver run_tests

notifications:
  slack: prominentedge:9VnNQcaSr6mHKSC2XHwEjkam
