language: python

branches:
  only:
    - master

virtualenv:
  system_site_packages: true

python:
  - "2.7"

install:
  - pip install .

before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)

before_install:
  - sudo apt-get update
  - sudo apt-get install gdal-bin

script:
  - paver run_tests

notifications:
  slack: prominentedge:9VnNQcaSr6mHKSC2XHwEjkam
